### ISSUE TITLE
Suggestion: Include licence in documentation

### ISSUE THREAD

**Issue by GadgetSteve** [jab/bidict#113]
The PyPi homepage is given as the[ Read the Docs site](https://bidict.readthedocs.io) and many legal types will not go beyond that in looking for the software licence so I would suggest including the licence on that page.

**Comment by jab** [comment]
Searching the PyPI project page for the word "license" immediately reveals the license:
![Screen Shot 2020-08-30 at 10 42 57 AM](https://user-images.githubusercontent.com/64992/91662246-22aa8b80-eaaf-11ea-9994-12f986f8f76c.png)

Same goes for the GitHub project page:
![Screen Shot 2020-08-30 at 10 46 41 AM](https://user-images.githubusercontent.com/64992/91662264-3a820f80-eaaf-11ea-9307-3f74553a80f8.png)

It also appears in a status badge right at the top of both of the above:
![Screen Shot 2020-08-30 at 10 41 11 AM](https://user-images.githubusercontent.com/64992/91662283-5e455580-eaaf-11ea-98fc-98234678f7cd.png)

...as well as the readthedocs site:
![Screen Shot 2020-08-30 at 10 36 54 AM](https://user-images.githubusercontent.com/64992/91662290-6ef5cb80-eaaf-11ea-96bb-638597a16a0c.png)

You can also find the associated Trove classifier, "OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)", right on the PyPI page, and other sites that aggregate such metadata across open source ecosystems, like libraries.io. See: https://libraries.io/pypi/bidict

I'm doubtful this is really an issue.

**Comment by GadgetSteve** [comment]
Joshua,

Sorry for the noise – I managed to miss the button on the read the docs page.

Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GadgetSteve** [comment]
Missed the button.
