### ISSUE TITLE
Not installable from GitHub release tarball

### ISSUE THREAD

**Issue by fabaff** [jab/bidict#115]
Using the source tarball from [releases](https://github.com/jab/bidict/releases) doesn't allow an installation.

```bash
$ tar -xzf bidict-0.21.2.tar.gz 
$ cd bidict-0.21.2/
$ python3 -m venv .
$ source bin/activate
$ python3 setup.py develop
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    setup(
  File "/home/bidict-0.21.2/lib64/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/bidict-0.21.2/lib64/python3.8/site-packages/setuptools/dist.py", line 446, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib64/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/bidict-0.21.2/lib64/python3.8/site-packages/setuptools/dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/bidict-0.21.2/.eggs/setuptools_scm-4.1.2-py3.8.egg/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/home/bidict-0.21.2/.eggs/setuptools_scm-4.1.2-py3.8.egg/setuptools_scm/__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "/home/bidict-0.21.2/.eggs/setuptools_scm-4.1.2-py3.8.egg/setuptools_scm/__init__.py", line 110, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/home/bidict-0.21.2'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

The tarball seems to be incomplete for the usage with `setuptools-scm`.

**Comment by jab** [comment]
Thanks for the report! The error message emitted by setuptools_scm that you pasted indicates that setuptools_scm does not currently support installing from GitHub release tarballs. (Its release notes for v4.0.0 seem to indicate otherwise, so I opened pypa/setuptools_scm#477 to ask about this.)

For now, if you are unable to install bidict via the recommended `pip install bidict` command [documented](https://bidict.readthedocs.io/#installation), and have to install from a GitHub release tarball instead, you can work around this as follows:
```
$ env SETUPTOOLS_SCM_PRETEND_VERSION=0.21.2 python setup.py develop
WARNING: The wheel package is not available.
running develop
running egg_info
creating bidict.egg-info
writing bidict.egg-info/PKG-INFO
writing dependency_links to bidict.egg-info/dependency_links.txt
writing requirements to bidict.egg-info/requires.txt
writing top-level names to bidict.egg-info/top_level.txt
writing manifest file 'bidict.egg-info/SOURCES.txt'
reading manifest file 'bidict.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bidict.egg-info/SOURCES.txt'
running build_ext
Creating /private/tmp/venv/lib/python3.8/site-packages/bidict.egg-link (link to .)
Adding bidict 0.21.2 to easy-install.pth file

Installed /private/tmp/venv/bidict-0.21.2
Processing dependencies for bidict==0.21.2
Finished processing dependencies for bidict==0.21.2
```

**Comment by jab** [comment]
By the way, using `pip install -e` is also recommended over `python setup.py develop`.

**Comment by jab** [comment]
Since this is the first I've heard of a user needing to do this, it would also be helpful to hear more about your use case if you can share.

**Comment by fabaff** [comment]
It's for building the RPM package for the Fedora Package Collection. So far, I patched out all `setuptools-scm` stuff because I prefer to use the upstream source better than the source tarballs which are available on PyPI and it saves me a dependency. Usually `setuptools-scm` works with the source tarballs from PyPI.

**Comment by jab** [comment]
Thanks for the context! I guess bidict isn't the only package in the Fedora Package Collection that uses setuptools_scm. Are the others getting similarly patched?

Btw, no response yet in pypa/setuptools_scm#477.

I can consider using one of the other options mentioned in https://packaging.python.org/guides/single-sourcing-package-version/.

**Comment by jab** [comment]
Just out of curiosity, why do you prefer using source tarballs from GitHub rather than from PyPI?
