### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by jab** [jab/bidict#187]
The [old logo](https://github.com/jab/bidict/blob/21beb84/assets/logo.png) is black on a transparent background, and was only designed for use on pages with light backgrounds. The logo is not visible on pages with dark backgrounds, which has become a much more common way for it to be displayed now that [GitHub supports dark mode](https://github.blog/changelog/2021-04-14-dark-and-dimmed-themes-are-now-generally-available/).

* SVG supports embedded CSS in `<style>` elements. Can `@media (prefers-color-scheme: dark)` be used in an SVG to make the same image file look good on both light and dark backgrounds? If so, if we switch the logo from PNGs to SVGs that use this trick, will it work everywhere the logo is displayed?
* Instead (or in addition), the logo could use other foreground colors that work well on both light and dark backgrounds. Python blue and yellow? (At that point, does it actually need a snake or two? Perhaps encircling a dictionary in a heart shape, or forming `{` braces around it `}` (as @lordmauve once mocked up)? A full redesign is not out of scope here :)

**Comment by jab** [comment]
Here is an attempt at a dark-mode-aware SVG:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 10" style="background: transparent">
  <style>
    path { fill: #333; }
    @media (prefers-color-scheme: dark) {
      path { fill: #aaa; }
    }
  </style>
  <path d="M7.944 4.792a.416.416 0 0 1 0 .416.392.392 0 0 1-.15.15l-5.83 3.527a.374.374 0 0 1-.201.058.405.405 0 0 1-.205-.055.386.386 0 0 1-.15-.153.428.428 0 0 1-.053-.208V1.473a.428.428 0 0 1 .053-.208.386.386 0 0 1 .15-.153.41.41 0 0 1 .407-.003l5.83 3.528a.438.438 0 0 1 .15.155z"/>
</svg>
```
And it seems to be working based on https://github.com/jab/test-dark-mode-aware-svg-in-markdown – nice.

**Comment by jab** [comment]
Here is an attempt at a dark-mode-aware SVG:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 10" style="background: transparent">
  <style>
    path { fill: #000; }
    @media (prefers-color-scheme: dark) {
      path { fill: #acf; }
    }
  </style>
  <path d="M7.944 4.792a.416.416 0 0 1 0 .416.392.392 0 0 1-.15.15l-5.83 3.527a.374.374 0 0 1-.201.058.405.405 0 0 1-.205-.055.386.386 0 0 1-.15-.153.428.428 0 0 1-.053-.208V1.473a.428.428 0 0 1 .053-.208.386.386 0 0 1 .15-.153.41.41 0 0 1 .407-.003l5.83 3.528a.438.438 0 0 1 .15.155z"/>
</svg>
```
But it doesn't seem to be working based on https://github.com/jab/test-dark-mode-aware-svg-in-markdown – `#000` is being used as the fill color, whether I have my GitHub theme set to light or dark.

**Comment by jab** [comment]
Switched to a white (rather than transparent) background as a quick interim fix in 0fd39b9.

**Comment by tomayac** [comment]
I think this falls under the "pros and cons" sections for each of the SVG embedding techniques outlined in this [guide](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web).

**Comment by jab** [comment]
Long-overdue thanks for that helpful link, @tomayac!

-----

Looks like GitHub has [hacked in their own support](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) for showing users different images based on their theme ([demo](https://github.com/jab/test-dark-mode-sensitive-images-in-markdown#githubs-anchor-filter-url-syntax-works)). I hope the web platform eventually provides a universal way to make such embedded content theme-sensitive.

**Comment by jab** [comment]
Oh nice: https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/
