### ISSUE TITLE
Consider removing slice and ~ syntax

### ISSUE THREAD

**Issue by lordmauve** [jab/bidict#19]
Some of the syntactic sugar in bidict causes a readability problem for me. Syntactic sugar is always going to be subjective, but I'd like to propose the removal of the overloading of slicing and bitwise negation - because ``.inv`` is succinct and covers all these cases without needing the sugar:

* ``~d`` is clearer written as ``d.inv``
* ``d[:key]`` is clearer written as ``d.inv[key]``.

These don't need to be explained/learned in the same way as they follow from the same clear rule.

Naturally this would be a big breaking change but if bidict is not yet at a 1.0 release then this could presumably still be considered.

**Comment by jab** [comment]
Thanks for opening this. Until now the feedback about the slice syntax has been unanimously positive, so it's valuable to hear another perspective. Eliminating the slice syntax would also allow me to get rid of the [caveat](https://bidict.readthedocs.org/en/latest/caveats.html#none-breaks-the-slice-syntax) about not being able to access a `None` value via slice syntax (usually a very rare edge case, but one that bugs me nonetheless).

That said, before I remove one of bidict's most appealing features for so many users, I'd need to get more feedback in favor of this, ideally supported by empirical evidence that the sugar is doing harm. In the meantime, there's nothing stopping users who prefer to use `.inv` from doing so.

**Comment by lordmauve** [comment]
The syntax isn't doing harm, but I feel (from experience) that it makes it less suitable for adoption in a large project.

Clear, non magical APIs seem to be key to making Python scale to large codebases. Every caveat that a class brings in adds to the cognitive load.

**Comment by jab** [comment]
After sleeping on it, I'm reopening this. Dropping support for the slice syntax, as well as ~, seems like it could increase bidict's [Python Zen](https://www.python.org/dev/peps/pep-0020/) on a few levels:
- Explicit is better than implicit.
- Simple is better than complex.
- Readability counts.
- Special cases aren't special enough to break the rules.
- There should be one-- and preferably only one --obvious way to do it.

It would also make the code cleaner and easier to maintain.

And being able to remove the ["None value" caveat](https://bidict.readthedocs.org/en/latest/caveats.html#none-breaks-the-slice-syntax) would be great.

I spent some time on GitHub code search surveying usage of slice and ~ syntax. Here is a sample of people whose code would break if I remove the syntax:
- @sgso ([example](https://github.com/sgso/marz/blob/d3f2951/marz.py#L230-L232))
- @cssmillie ([example](https://github.com/cssmillie/otu/blob/d62ac265/seqdb.py#L25-L32))
- @PersonalAnalytics ([example](https://github.com/PersonalAnalytics/Personal-analytics/blob/11cfc130/processing_layer/scripts/seqdb.py#L30-L40))
- @prologic ([example](https://github.com/prologic/charla/blob/5390519/charla/models.py#L35))
- @Nuullll ([example](https://github.com/Nuullll/MIPS-interpreter/blob/e62f90a0/interpreter.py#L59))
- @PIA-Group ([example](https://github.com/PIA-Group/BioSPPy/blob/5756efc/biosppy/biometrics.py#L656))
- @AngryDevelopersLLC ([example](https://github.com/AngryDevelopersLLC/res-scheduler/blob/b6c2c5f3/res/scheduling/worker.py))
- @not-na ([example](https://github.com/not-na/packetmq/blob/7a31c9c/packetmq/__init__.py#L75-L78))
- @ajmarks ([example](https://github.com/ajmarks/gymnast/blob/2184176/gymnast/pdf_elements/fonts/base_font.py#L184)
- @makrai ([example](https://github.com/makrai/efnilex-vect/blob/01173fd6/lintrans14.py#L208))

Everyone please give feedback here, and please spread the word to other bidict users. I'm leaning toward going through with this, but if users' feedback trumps the rationale above, I won't.


While we're at it, I'm also thinking of removing namedbidict. If you have any feedback on that, please chime in on #23.

Thanks everyone.

**Comment by ajmarks** [comment]
My project can easily be converted if you decide to change.  I may just go ahead and do that preemptively.

**Comment by prologic** [comment]
What would the syntax change to?

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by jab** [comment]
@prologic You would use `b.inv` as you can do now. So `b[:val]` would become `b.inv[val]`. And just use `b.inv` rather than `~b`.

**Comment by prologic** [comment]
I see; thanks for that. I'm happy for this change to go ahead personally. I would however prefer something like ``b.inverse[key]`` however. Or even better: ``b.inverse(key)``

**Comment by jab** [comment]
Thanks @prologic, glad you're happy for this to go ahead.

Changing to `.inverse` would mean another breaking change, and could annoy users who prefer the more concise `.inv` (myself included). Could add it `.inverse` as an alias for `.inv`, but that seems against the spirit of this change (one obvious way to do things). Interested to hear more feedback though.

As for the callable rather than getitem syntax, again another breaking change, and harmfully masks the fact that `b.inv` is itself a bidict, and so should be accessed like one. Would reject anything that broke isomorphism between `b` and `b.inv`.

**Comment by jab** [comment]
FWIW, in my survey of bidict usage, I did encounter instances of people preferring to use `b.inv[val]` even with `b[:val]` available ([example](https://github.com/alcemirfernandes/pynguin/blob/631330a/lib/pynguin/mw.py#L2032)). /cc @alcemirfernandes

**Comment by prologic** [comment]
Fair points :) Go for it!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by not-na** [comment]
My project could also easily be changed to a new syntax, if required.

**Comment by jab** [comment]
PR open for this in #25

**Comment by belevtsoff** [comment]
+1 for removal. That said, the project's been around for a while, so introducing backwards-incompatible changes at this point might do more harm than good.

**Comment by Nuullll** [comment]
My project could also easily be changed to a new syntax.

Thanks.


From Meizu MX4

-------- Original message --------
Sender: jab <notifications@github.com>
Time: Thu 11/26 01:53
To: jab/bidict <bidict@noreply.github.com>
Cc: Yilong Guo <vfirst218@gmail.com>
 Subject: Re: [bidict] Consider removing slice and ~ syntax (#19)

**Comment by jab** [comment]
Thanks for the feedback, everyone. Just merged the branch that implements this.

**Comment by prologic** [comment]
Ping this issue when you've pushed a new release to PyPi :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by jab** [comment]
Will do.

**Comment by jab** [comment]
@prologic Released!

**Comment by prologic** [comment]
:+1:

**Comment by pjsg** [comment]
Unfortunately our system just used the latest version of bidict -- so our system died when 0.10 was released (we used the slice syntax). This (again) teaches us the importance of version locking...

**Comment by jab** [comment]
@pjsg Sorry to hear you got bit by the breaking changes. I hope the bugfixes and other improvements in 0.10+ make it worth upgrading. Btw, just invited you to join https://gitter.im/jab/bidict. I always ping everyone in there with news (and Gitter can email you messages you missed while not in the chat), in case you're interested. Please feel free to stop by and say hi / share your use case any time.

**Comment by sublee** [comment]
It should warn `DeprecationWarning` first.

**Comment by jab** [comment]
@sublee Once bidict reaches 1.0, yes, but in the meantime, I'm following [semver.org](http://semver.org/) which says:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Hope that seems fair. FWIW, as of closing #23, I don't foresee making any further breaking changes before 1.0. My current thinking is bidict will be ready for 1.0 as soon I make sure that its performance is about equal to keeping 2 inverse dicts in sync manually (see #9). I may first also add support for `orderedbidict` in a 0.11 release (see #29).

I invited you to join https://gitter.im/jab/bidict. As I said above, I always ping everyone in there with news (and Gitter can email you messages you missed while not in the chat), in case you're interested. Please feel free to stop by and say hi / share your use case any time. I love getting to know bidict's users better.

**Comment by sublee** [comment]
@jab Thanks to good answer. Now I agree to your thinking.
