### ISSUE TITLE
consider removing namedbidict

### ISSUE THREAD

**Issue by jab** [jab/bidict#23]
To enable me to focus better on more core functionality, I'm considering removing namedbidict. The value it has provided doesn't seem worth the maintenance burden.

Here is a sample of people/orgs whose code would break if this happens:
- @venmo ([example](https://github.com/venmo/btnamespace/blob/e4b269f9a/btnamespace/actions.py#L11))
- @NEU-Libraries ([example](https://github.com/NEU-Libraries/alma-analytic-tools/blob/e554b76f/RequestObject.py#L108)
- @maddyloo ([example](https://github.com/maddyloo/miniBibServer/blob/9750e1e/latex_accents.py#L9))
- @lig ([example](https://github.com/lig/pyfusegridfs/blob/05104ea2a/fusegridfs/fuse.py#L30))
- @adrinjalali ([example](https://github.com/adrinjalali/Network-Classifier/blob/8f4fd4c/read_vantveer.py#L124))
- @belevtsoff ([example](https://github.com/belevtsoff/earlPipeline/blob/985f2f9b/earlpipeline/backends/base_simple_engine.py#L17))

Everyone please give feedback here, and please spread the word to other bidict users. I'm leaning toward going through with this, but if users' feedback trumps the rationale above, I won't.

**Comment by lig** [comment]
@jab Thanks for notice. That my code does not completely work anyway. It was just a try around.

**Comment by belevtsoff** [comment]
@jab hi, thanks for the notice. It's quite sad that bidict is going cuz I found it very handy and much more readable than the unusual slice syntax. Also, some parts of https://github.com/belevtsoff/earlPipeline will break. Can you give some more detail on why is its maintenance particularly tedious?

**Comment by jab** [comment]
@belevtsoff wrote:
> It's quite sad that bidict is going

(Just to make sure this was a typo, `bidict.bidict` isn't going anywhere. This issue is proposing to remove `bidict.namedbidict`.)

> why is its maintenance particularly tedious?

- It's a non-essential feature that adds complexity and takes focus away from more essential things.
- I have yet to see anyone create more than a single instance of a `namedbidict`-created type. This suggests that namedbidict could be overkill. Compare this with namedtuple, where it's common to create multiple instances of the same namedtuple-created type.
- The same intent can be expressed clearly and with less ceremony just using well-named variables with a regular bidict:
```python
>>> name_by_level = bidict({'DEBUG': 10, 'INFO': 20})
>>> current_levelname = name_by_level[logger.getLevel())
>>> logger.setLevel(name_by_level.inv['INFO'])
>>> # compare to:
>>> LevelMap = namedbidict('LevelMap', 'name', 'level')
>>> levelmap = LevelMap({'DEBUG': 10, 'INFO': 20})
>>> current_levelname = levelmap.for_level[logger.getLevel())
>>> logger.setLevel(levelmap.for_name['INFO'])
```
- namedtuple is [implemented in only 19 SLOC](https://github.com/jab/bidict/blob/master/bidict/_named.py). Not too big to add in your application's code if you really miss it.

Speaking of well-named variables, looking at [your code](https://github.com/belevtsoff/earlPipeline/blob/985f2f9b/earlpipeline/backends/base_simple_engine.py#L17), you're passing `'by_name'` and `'by_instance'` as the accessor names for keys and values, but the intention would be for you to pass just `'name'` and `'instance'`, since namedbidict already prepends "for_" to the names you pass when creating the accessors. (This has been the case since at least version 0.2.1; see [here](https://github.com/jab/bidict/blob/a409c25/bidict.py#L792-L806) for example.) So your own code is an example that namedbidict isn't clear or simple enough.

Interested to hear in any further feedback people may have.

**Comment by jab** [comment]
(I see, it looks like you're using a very old version (0.1.2), when bidict was not yet prepending "for_". Editing my previous comment.)

**Comment by jab** [comment]
> and much more readable than the unusual slice syntax

Did you know about `.inv`? As documented in the [intro](https://bidict.readthedocs.org/en/latest/intro.html), the slice syntax is not required; you can always use `b.inv[val]` instead.

Btw, sounds like you'd vote for #19, which proposes to remove support for the slice syntax. Please see discussion there.

**Comment by belevtsoff** [comment]
@jab, so it looks like my code was broken anyway, because of the new `for_` syntax :)

> Just to make sure this was a typo
Yeah, that was definitely a typo

> Did you know about .inv?
No. The last time I used bidict it was a single file on the bitbucket :)

Anyway, I didn't touch the project I was referencing for more than a year, so removing namedbidict can be a good stimulus to wipe the dist off it. So I don't have any serious arguments against removing namedbidict except that I kinda liked the idea

**Comment by adrinjalali** [comment]
@jab, thanks for the notice. I indeed don't use the inverse relationship in my code anyway. But I liked the idea. Sorry to hear it's too much burden maintaining it.

**Comment by jab** [comment]
I'm going to leave namedbidict in for now. May reconsider later.
