### ISSUE TITLE
List comprehension issue possibly Windows related

### ISSUE THREAD

**Issue by ApatheticsAnonymous** [jab/bidict#27]
Performing a list comp with a bidict results in a 'not defined' error on Windows. Ive tried the same code on OSX 10.10 and it works fine.

In [1]: import bidict

In [2]: bd = bidict.bidict({1: 'a', 2: 'b', 3 : 'c'})

In [3]: bd[:'a']
Out[3]: 1

In [4]: names = [ 'a', 'b', 'c']

In [5]: names = ['a', 'b']

In [6]: keys = [ bd[:x] for x in names ]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
----> 1 keys = [ bd[:x] for x in names ]

NameError: name 'bd' is not defined

**Comment by jab** [comment]
There should be no reason this would happen, and I could neither reproduce with Python 2 nor 3 on Windows:

![screen shot 2015-12-15 at 13 35 46](https://cloud.githubusercontent.com/assets/64992/11820246/828a8f3e-a331-11e5-8734-0e305e27f0db.png)

![screen shot 2015-12-15 at 13 39 45](https://cloud.githubusercontent.com/assets/64992/11820251/86cdb134-a331-11e5-8006-9c1566949e32.png)

Did you copy/paste the code above from different ipython sessions, where `bd` was not defined in one of them? If you save this code in a file like `test.py` and then run it with `python.exe test.py`, does it work?

Closing this for now as it seems like the issue's on your end, not bidict's. If you can provide more evidence to the contrary, or even access to a Windows environment that demonstrates as much, will reopen and take another look.

**Comment by ApatheticsAnonymous** [comment]
Ive confirmed this issue is not related to bidict. It happens in IPython for regular dictionaries as well but only when I create the shell with:

    from IPython import embed
    
    embed()

Perhaps IPython does not support being imported via "from, import". Thanks for looking into it anyway.
