### ISSUE TITLE
mypy type inference change in 0.23.0

### ISSUE THREAD

**Issue by brianmedigate** [jab/bidict#310]
In version 0.22.1, mypy would automatically understand the type of a bidict created from a dict based on the type of the underlying dict:

```python
import bidict

a = bidict.bidict({"A": 1})
reveal_type(a)
# note: Revealed type is "bidict._bidict.bidict[builtins.str, builtins.int]"
```

But in 0.23.0, it thinks the type is `bidict[Any, Any]`:

```python
import bidict

a = bidict.bidict({"A": 1})
reveal_type(a)
# note: Revealed type is "bidict._bidict.bidict[Any, Any]"
```

I'm not sure if this was intentional or not, or if can be easily changed, but the previous behavior was convenient.

I'm using mypy 1.8.0.

**Comment by jab** [comment]
Thanks for reporting, this is definitely not intentional!

I can't reproduce this with Python 3.10, 3.11, or 3.12, but I can with Python 3.8 and 3.9. Can you confirm what Python version you're using, and whether it reproduces for you if you use Python ≥ 3.10?

**Comment by brianmedigate** [comment]
Thanks!

Yeah, I was running on python 3.8 (3.8.18 specifically).

It doesn't reproduce for me on 3.10, so it looks like we're seeing the same thing.

**Comment by jab** [comment]
@brianmedigate thanks for confirming. My latest revision should fix this. If you would like to confirm the fix works for you and report back, you can run e.g. `pip install --upgrade 'https://github.com/jab/bidict/archive/refs/heads/main.zip'` to upgrade to and test against the latest development version.

**Comment by brianmedigate** [comment]
Fix works for me, thanks!
And very impressive turnaround time, kudos :clap:

**Comment by jab** [comment]
Thanks for confirming, and [thanks](https://bidict.readthedocs.io/en/main/thanks.html#:~:text=brian%20maissy) again for reporting this!

Fix [released in 0.23.1](https://github.com/jab/bidict/releases/tag/v0.23.1) and [published to PyPI](https://pypi.org/project/bidict/).

**Comment by brianmedigate** [comment]
I found an edge case where the type inference is still lost. It's really not critical, mostly sharing it with you just out of curiosity as to what could cause it if you have any ideas. Definitely don't invest any significant amount of time on this, at least not on my account.

Types inheriting from types defined in cython become `Any` after being put into a `bidict`:

`test1.py`:
```python
import bidict
from test2 import Base

class Foo(Base):
    pass

class Bar(Base):
    pass

a = {Foo(): Bar()}
reveal_type(a)

b = bidict.bidict(a)
reveal_type(b)
```

`test2.pyx`:
```python
class Base:
    pass
```

```sh
$ cythonize test2.pyx
$ mypy test1.py
test1.py:13: note: Revealed type is "builtins.dict[test1.Foo, test1.Bar]"
test1.py:15: error: Need type annotation for "b"  [var-annotated]
test1.py:16: note: Revealed type is "bidict._bidict.bidict[Any, Any]"
```

**Comment by jab** [comment]
Hi @brianmedigate, I tried to reproduce this, but (once I added the missing .pyi type stub file for test2.pyx so that mypy would not fail with an import-not-found error), I couldn't reproduce:
```
❯ python -VV  # ensured I'm using 3.8 like you are
Python 3.8.18 (default, Aug 24 2023, 19:48:18)
[Clang 16.0.6 ]

❯ python -m pip list  # here are the versions of mypy (etc.) I tested with
Package           Version
----------------- -------
bidict            0.23.1
Cython            3.0.8
mypy              1.8.0
mypy-extensions   1.0.0
pip               24.0
setuptools        56.0.0
tomli             2.0.1
typing_extensions 4.10.0


❯ cat setup.py
from setuptools import setup
from Cython.Build import cythonize
setup(
    ext_modules = cythonize("test2.pyx")
)


❯ cat test2.pyx
class Base:
    pass


❯ python setup.py build_ext --inplace
Compiling test2.pyx because it changed.
[1/1] Cythonizing test2.pyx
...
building 'test2' extension
creating build
creating build/temp.macosx-11.0-arm64-3.8
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/w360dcffcwkzwbi842kf937sakil3bg1-libxcrypt-4.4.36/include -I/tmp/issue310/.venv/include -I/nix/store/gds5gm7jak0sgb9cyw9qrb554y786i3i-python3-3.8.18/include/python3.8 -c test2.c -o build/temp.macosx-11.0-arm64-3.8/test2.o
...
copying build/lib.macosx-11.0-arm64-3.8/test2.cpython-38-darwin.so ->


❯ cat test1.py
import typing as t
from test2 import Base
from bidict import bidict
from typing_extensions import assert_type

class Foo(Base):
    pass

class Bar(Base):
    pass

a = {Foo(): Bar()}
assert_type(a, t.Dict[Foo, Bar])

b = bidict(a)
assert_type(b, bidict[Foo, Bar])


❯ python test1.py  # succeeds


❯ mypy test1.py  # fails due to missing type stubs
test1.py:3: error: Cannot find implementation or library stub for module named "test2"  [import-not-found]
...

❯ echo 'class Base: ...' > test2.pyi  # add missing type stubs


❯ mypy test1.py
Success: no issues found in 1 source file
```

Any ideas?

**Comment by brianmedigate** [comment]
hmm interesting, I don't have a `.pyi` file, I have `ignore_missing_imports = True` configured in my `mypy.ini`

**Comment by jab** [comment]
In that case I’d have to see more test cases to tell if this is still an issue in bidict vs. in mypy (or even just mypy behaving as expected under these conditions).

**Comment by brianmedigate** [comment]
ok then never mind, thanks!
