### ISSUE TITLE
Recommended performant alt for `namedbidict` 

### ISSUE THREAD

**Issue by rtbs-dev** [jab/bidict#314]
I've been using your implementation of namedbidict for a while now, after reading the post in your "learning" section, but just now seeing it's been removed after trying to re-run some code from a couple years ago. 

It was a pretty elegant way to quickly make simple classes that  could maintain the mapping between categorical names and id's (tbh I preferred using it as a core data structure to pandas' `Categorical` since it didn't require array types, etc.). A list of `namedbidict("TokenID","token","id")` objects was a super easy way to manage the names and ID's of arbitrary things at super-low overhead. 

Any preferred suggestions from here? I get the need to simplify, for sure; just figured if I was one of the "low-usage" folks maybe the original designer had an alternative idea for accomplishing the same thing :) 

Thanks so much for this amazing library, but honestly also for all the commentary and write-ups, they've been immensely helpful over the years!

**Comment by jab** [comment]
Closing this but please feel free to continue the discussion.
