### ISSUE TITLE
Cannot inherit loosebidict

### ISSUE THREAD

**Issue by mlenzen** [jab/bidict#34]
import bidict
    class Sub(bidict.loosebidict):
         pass
    b = Sub()
    b['a'] = 1
    ....
    RecursionError: maximum recursion depth exceeded while calling a Python object

This is because you are calling ``super(self.__class__, self)`` instead of ``super()``

**Comment by jab** [comment]
Hi @mlenzen, good to see you again after chatting in mlenzen/collections-extended#42, and thanks so much for the report! This is actually already fixed on the 0.12.0-dev branch, and in 9ac0476 I just committed a passing test to demonstrate this. I've just been waiting on someone to review my pull request (#33) before I merge that branch to master and cut the 0.12.0 release. If you have any time and interest in taking a look, I'd much appreciate your review! Another contributor said he might be able to get to it by the end of the week, but it'd be great to have another pair of eyes on it, and he may not get to it soon after all.

**Comment by jab** [comment]
Hi @mlenzen, I'm just waiting on anyone to finish reviewing #33 before releasing the fix for this as part of 0.12.0. Would you have any interest in taking a look at that PR?
