### ISSUE TITLE
Unnecessary assignment

### ISSUE THREAD

**Issue by tjomk** [jab/bidict#4]
https://github.com/jab/bidict/blob/master/bidict.py#L426 - unless I miss something this looks like a unnecessary line. After doing `self._fwd = self._bwd` you are assiging `self._fwd` (which already has the value of `self._bwd`) back to `self._bwd`.

Any reason for doing this?

**Comment by jab** [comment]
Read it again and note the difference between `self` and `inv`.

**Comment by jab** [comment]
Thank you for the code review in any case. If you'd like to share how you found out about bidict and what you're using it for, I'd be interested to hear.

**Comment by tjomk** [comment]
Ah, it was in plain sight. Not sure why I found this suspicious.

Read about this in Pycoder's Weekly: http://pycoders.com/

**Comment by jab** [comment]
Didn't realize you were from Pycoder's Weekly. Thanks for putting bidict in this week!

And I think something about the variable names makes it easy to read something like `inv._bwd = self._fwd` and think `self._bwd = self._fwd` by mistake. Maybe renaming `inv` "inverse" would make it easier to parse. If you spot anything else that looks funny in the code, please don't hesitate to mention.

Thanks again!
