### ISSUE TITLE
v0.14.0 breaks viewitems() with Python2.7

### ISSUE THREAD

**Issue by rsanger** [jab/bidict#48]
viewitems() is no longer working

```
from bidict import bidict
d = bidict(a="b")
d.viewitems()
```
Now returns an error:
TypeError: __init__() takes exactly 2 arguments (1 given)

Looks like this is the cause [033083ca](https://github.com/jab/bidict/commit/033083ca#diff-d31a7186b3cebec9a3801b0eade00001L362)

Thanks,

**Comment by jab** [comment]
Thanks so much for reporting, @rsanger! Should be fixed in #49. Would you like to review before I merge?

**Comment by rsanger** [comment]
Thanks for the quick fix :)

**Comment by jab** [comment]
My pleasure. Just released v0.14.1 with the fix. Please let me know if you hit any other issues!

Btw, I'm always interested to hear more about how people are using bidict, so if you'd like to share more about your use cases, it'd be a pleasure to hear more! You can always feel free to message me privately on Gitter or in the [bidict Gitter chat room](https://gitter.im/jab/bidict), where I also post release announcements (very low volume). You can also [follow bidict on Sibbell](https://sibbell.com/github/jab/bidict/) to be automatically notified when there's a new release.

Thanks again for reporting, and all the best 😊
