### ISSUE TITLE
refactor tests

### ISSUE THREAD

**Issue by jab** [jab/bidict#8]
- Port existing doctests to a combination of property-based tests (#6) and traditional separate py.test tests. When this is done docstrings can be condensed to make the documentation more quickly digestible.
- New test layout should also accommodate performance (#9) and fuzz (#10) tests.
- Switch to py.test for running all tests. Update:
  - setup.py
  - test.py
  - .travis.yml
  - tox.ini
  - docs
    - https://bidict.readthedocs.org/
    - https://github.com/jab/bidict#readme
    - https://github.com/jab/bidict/blob/master/CONTRIBUTING.rst

**Comment by jab** [comment]
Created https://github.com/jab/bidict/tree/tests_refactor branch for this.

**Comment by jab** [comment]
Pushed a big refactoring to the branch.
- broke up single bidict.py module into multiple separate modules inside `bidict` dir
- condensed docstrings by moving documentation into separate pages and preferring hypothesis- and pytest-based tests over doctests

**Comment by jab** [comment]
Hey @tomviner, just a heads up that I merged all the recent progress on branches back to master and rebased. I think `git fetch && git reset --hard origin/master` should do the trick to avoid conflicts in any clones. Hope being able to branch off master again makes things easier going forward.

**Comment by tomviner** [comment]
The changes are great, and the splitting up makes things much easier to digest, especially for fresh devs. 

It is however frowned upon to edit the history of (i.e. rebase) master branch. It's considered public and so you could be messing someone else up. In this case probably just me that needed special commands to recover, just `git pull --rebase origin master` for me, but it's a wise principle in general.

**Comment by jab** [comment]
Oh no, my apologies, @tomviner. I really hope I didn't cause you any trouble. I've had so little visibility into anyone else using or working on bidict for so long that I've gotten into the bad habit of rebasing master decently often. If ever there were a time to be more careful it would be now. Sorry for the lack of consideration, and won't happen again.

**Comment by tomviner** [comment]
No probs, it's fine for me, just wanted to pass on the advice for the future.

**Comment by tomviner** [comment]
My work flow that I've built up from interacting with many teams working on a single codebase, is:
- master can never have history edited*
- when pulling any branch don't allow `git pull` to make a merge commit, do `git pull --rebase origin <branch>` instead
- feature branches should be rebased often to keep up with master's progress with `git fetch --all; git pull --rebase origin master`

I've got some aliases that make this really easy:
- `alias gfa='git fetch --all`
- `alias gr_master='git pull --rebase origin master'`
- `alias gr_this_branch='git pull --rebase origin $(git rev-parse --abbrev-ref HEAD)'`

so I do it without thinking now.

* having said that I did accidentally push a whole repo on top of a whole other repo's master branch the other day at work! So in for a penny, in for a pound, force pushed the fix before anyone noticed :-)

**Comment by jab** [comment]
Thanks for the explanation and those aliases, makes sense and much appreciated!
