### ISSUE TITLE
[Doc] subclass of object are hashable by default in python 3.7.1

### ISSUE THREAD

**Issue by pumbaacave** [jab/bidict#82]
using ipython with python 3.7.1, I found that
```python
In [95]: class Temp(object):
    ...:     pass
    ...:

In [96]: a = Temp()

In [97]: hash(a)
Out[97]: -9223372036574570836
```
contradict with the descrpition
>This is consistent with the fact that object implements __hash__(), but subclasses of object are not hashable by default.

in [learn from bidict](https://bidict.readthedocs.io/en/master/learning-from-bidict.html)
Do i make this right because the behaviour of hash in new version of python differs
or just I misunderstand sth?

**Comment by jab** [comment]
```
Python 3.7.1 (default, Nov  6 2018, 18:49:54)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: class Temp(object):
   ...:     def __eq__(self, other):
   ...:         return False
   ...:

In [2]: a = Temp()

In [3]: hash(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-57b555d30865> in <module>
----> 1 hash(a)

TypeError: unhashable type: 'Temp'
```

Just a misunderstanding -- I meant for types with a custom `__eq__` implementation. Added that in e443b0f, hopefully clearer now?

**Comment by pumbaacave** [comment]
Thanks for the clear explanation, and through reading the doc now I know class implement 
__eq__ only is not hashable
