### ISSUE TITLE
release wheels for Python 2

### ISSUE THREAD

**Issue by gaborbernat** [jab/bidict#83]
https://files.pythonhosted.org/packages/b0/d8/f324b2a7a9fa098b800dcb4b34aa3f2df955caf9235f20d351ceed9e7c22/bidict-0.17.5-py3-none-any.whl shows that the wheel is only python 3 compatible, can we release the package as both python 2 and 3 compatible? https://wheel.readthedocs.io/en/stable/user_guide.html?highlight=universal#building-wheels

**Comment by jab** [comment]
Thanks for reporting this! I can create a Python 2 wheel for 0.17.5 and upload it manually. For doing this automatically for future releases, is this something you’d be interested in contributing? Take a peek at the “release” part at the end of .travis.yml.

**Comment by gaborbernat** [comment]
I don't think you need to modify the release process. You can create a single both pyhton2/3 wheel by just adding the linked settings in setup.cfg.

**Comment by gaborbernat** [comment]
Thanks!
