### ISSUE TITLE
Thoughts: More than bidirectional functionality?

### ISSUE THREAD

**Issue by hbrooks** [jab/bidict#91]
Hi All,

I came across `bidict` while searching for a more general application of the functionality in this helpful repo.  I was wondering if anyone here can point me towards the data structure I'm looking for or help me expand on `bidict` to build it.  

The data structure I'm looking for can, in `O(1)` time, go from an element of a collection to getting the rest of the elements in that collection.  If the collections are of size 2, this boils down to what `bidict` does now.  In the case where they're not, like
```
collection = [
    [1, 'hola', 'hello'],
    [2, 'audios', 'goodbye'],
]
```
I'm hoping to index like `collection['goodbye']` and get `[2, 'audios', 'goodbye']`.  The inclusion of the key used to index in the return structure doesn't matter to me.

**Questions**:
1.  Has anyone else had the need for this type of in memory data structure?  Was the `O(1)` indexing constraint relevent?
1.  Can `bidict` be easily expanded to do this?  

**Solutions**:
1.  It would be easy to filter the collection for the subcollection of interest, but that's an `O(n)` process.
1.  As long as all the values are unique across sub collections, I was thinking I could keep a large dictionary of elements in the sub collections to that sub collection.  This approach would be close to what `bidict` does, but with the added constraint that all the elements are unique.  My understanding is that `bidict` currently only requires that all the keys are unique and that all the values are unique.  Can someone validate this?  If true, is that why `bidict` doesn't currently take this approach?  

**Use Case**
The real world use case is to avoid making a database call to get simple, unchanging information out of a relational database table.  For example, we might store permission levels in an application DB as integers but refer to them in API responses and errors different strings.  All elements of the collection relate to the same idea, they're just different representations.  One alternative to having a structure like this is to have lots of translation functions.   Ex: `def db_int_to_API_representation(db_int):`.  However, as the number of entries in the collections grows, the number of functions needed could grow as its factorial.  A more realistic example collection is:
```
permissions = [
    [1, 'readOnly', 'read_only', 'READ'],
    [2, 'writeOnly', 'write_only', 'WRITE'],
    [3, 'readWrite', 'read_write', 'READWRITE'],
]
```

**Comment by cjgibson** [comment]
It _feels_ like you'd be best served in this case by just leveraging Python's builtin `dict`, potentially with something like:

```python
class AliasDict(object):
    """ Affords simple lookup of a set of elements using any member of the set
      >>> from alias_dict import AliasDict
      >>> permissions = [
      ...     [1, 'readOnly', 'read_only', 'READ'],
      ...     [2, 'writeOnly', 'write_only', 'WRITE'],
      ...     [3, 'readWrite', 'read_write', 'READWRITE'],
      ... ]
      >>> test = AliasDict(permissions)
      >>> test.get(1)
      [1, 'readOnly', 'read_only', 'READ']
      >>> test.get('WRITE')
      [2, 'writeOnly', 'write_only', 'WRITE']
      >>> test.get('read_write')
      [3, 'readWrite', 'read_write', 'READWRITE']
      >>> test.get('unknown')
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "alias_dict.py", line 36, in get
          return self.__lookup[alias]
      KeyError: 'unknown'
    """
    
    def __init__(self, aliased_sets):
        self.__lookup = {}
        self.add(*aliased_sets)
    
    def add(self, *aliased_sets):
        for aliased_set in aliased_sets:
            for alias in aliased_set:
                if alias in self.__lookup:
                    raise ValueError("All aliased sets must be independent")
                self.__lookup[alias] = aliased_set
    
    def get(self, alias):
        return self.__lookup[alias]
```

Albeit with the addition of some logic to handle the desired (im)mutability of the `AliasDict` during program runtime. As far as I'm aware, the default `bidict` objects maintain a forward mapping of keys to values and a reverse mapping of values to keys - requiring uniqueness in the key sets of both maps in order to ensure that lookup in either direction is sane.

**Comment by hbrooks** [comment]
Thanks for your insight @cjgibson, I ended up going with the approach you suggested!

**Comment by jab** [comment]
Thanks for beating me to giving an answer, @cjgibson, and thank you for the question, @hbrooks -- glad to hear you were able to go with @cjgibson's approach!

I'll close this as out of scope for bidict, and recommend having any continued discussion somewhere else, e.g. [comp.lang.python](https://wiki.python.org/moin/CompLangPython) (and feel free to link to that from here if you end up discussing further).

Thanks for using bidict, and hope it's working well for any of your (only-) bidirectional mapping needs.

P.S. I'm always interested to hear more about how people are using bidict, so if either of you would like to share more about your use cases, it'd be a pleasure to hear more. You can always feel free to post in the [bidict Gitter chat](https://gitter.im/jab/bidict), where I also post release announcements (very low volume), or DM me on Gitter, and I'll get back to you as soon as I can.
