### ISSUE TITLE
[Feature Request] Multiple Values for a key

### ISSUE THREAD

**Issue by SmartManoj** [jab/bidict#92]
a={
2:(3,4),
5:3
}
a_inv={
	3:(2,5),
	4:2,
}
Is it possible to achieve using bidict?

**Comment by jab** [comment]
First, welcome to the bidict tracker, @SmartManoj!

The data structure you’re looking for is not a bidirectional mapping, and therefore falls outside the scope of bidict, so I am closing this. A bidirectional mapping associates a single forward key with a single inverse key, both of which must be hashable. See #91 for more info and a possible alternative you can use.
